version: '3.8'

services:
  mysql-dev:
    image: mysql:8.3.0
    container_name: mysql-dev
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
    volumes:
      - ./db-data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal-dev

  adminer-dev:
    image: adminer:4.8.1-standalone
    container_name: adminer-dev
    ports:
      - '8080:8080'
    depends_on:
      - mysql-dev
    networks:
      - internal-dev

networks:
  internal-dev:
    external: false